---

- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes

- name: reboot
  reboot:
    pre_reboot_delay: 60

- name: Flush Handlers, best practice
  meta: flush_handlers
